# Configuración global
authoritative;
default-lease-time 600;
max-lease-time 7200;

# Añade esto arriba del todo para que afecte a todas las redes
option domain-name "jankesto.local";
option domain-search "jankesto.local";

# Subred Gestión
subnet 192.168.10.0 netmask 255.255.255.0 {
  option routers 192.168.10.1;
  option domain-name-servers 192.168.10.1;

  # Reserva para servidor importante en gestión
  host servidor_wazuh {
    hardware ethernet 52:54:00:01:56:1a; 
    fixed-address 192.168.10.10;
  }
   # Reserva para servidor importante en gestión
  host admin_server {
    hardware ethernet 52:54:00:01:42:c5;
    fixed-address 192.168.10.20;
  }
}

# Subred Usuarios (ejemplo enp2s0)
subnet 192.168.20.0 netmask 255.255.255.0 {
  range 192.168.20.100 192.168.20.200;
  option routers 192.168.20.1;
  option domain-name-servers 192.168.20.1;
}

# Subred DMZ
subnet 192.168.30.0 netmask 255.255.255.0 {
  option routers 192.168.30.1;
  option domain-name-servers 192.168.30.1;

  # Reserva para servidor web en DMZ
  host servidor-web-dmz1 {
    hardware ethernet 52:54:00:02:ee:b8; 
    fixed-address 192.168.30.10;
  }

  # Reserva para servidor web en DMZ
  host servidor-web-dmz2 {
    hardware ethernet 52:54:00:02:33:9e;
    fixed-address 192.168.30.20;
  }
}
