#!/usr/sbin/nft -f

flush ruleset

define IF_WAN    = "enp1s0"
define NET_WAZUH = 192.168.10.0/24
define NET_USERS = 192.168.20.0/24
define NET_DMZ   = 192.168.30.0/24
define WAZUH_IP  = 192.168.10.10
define DMZ_WEB   = 192.168.30.10
define ADMIN_IP  = 192.168.10.20
define MGMT_TCP  = { 22, 80, 443, 5380 }

table inet filter {
    chain input {
        type filter hook input priority 0; policy drop;

        ct state established,related accept
        ct state invalid drop
        iif "lo" accept

        ip saddr $ADMIN_IP tcp dport $MGMT_TCP accept

        ip saddr $NET_WAZUH udp dport 53 accept
        ip saddr $NET_WAZUH tcp dport 53 accept
        ip saddr $NET_USERS udp dport 53 accept
        ip saddr $NET_USERS tcp dport 53 accept
        ip saddr $NET_DMZ   udp dport 53 accept
        ip saddr $NET_DMZ   tcp dport 53 accept
    }

    chain forward {
        type filter hook forward priority 0; policy drop;

        ct state established,related accept
        ct state invalid drop

        ip saddr $NET_USERS ip daddr $DMZ_WEB tcp dport { 80, 443 } accept
        ip saddr $NET_WAZUH ip daddr $DMZ_WEB tcp dport { 22, 80, 443 } accept

        ip saddr $NET_USERS ip daddr $WAZUH_IP tcp dport { 1514, 1515, 55000 } accept
        ip saddr $NET_DMZ   ip daddr $WAZUH_IP tcp dport { 1514, 1515, 55000 } accept

        ip saddr $NET_USERS oifname $IF_WAN accept
        ip saddr $NET_DMZ   oifname $IF_WAN accept
        ip saddr $NET_WAZUH oifname $IF_WAN accept
    }
}

table ip nat {
    chain postrouting {
        type nat hook postrouting priority 100;
        oifname $IF_WAN masquerade
    }
}
